version: "3.8"

services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  hmdm:
    image: headwindmdm/hmdm:0.1.5
    restart: unless-stopped
    ports:
      - "8189:8080"
      - "31000:31000"
    depends_on:
      - db
    environment:
      SQL_HOST: db
      SQL_USER: ${SQL_USER}
      SQL_PASS: ${SQL_PASS}
      SQL_BASE: ${SQL_BASE}
      PROTOCOL: http
      BASE_DOMAIN: ${BASE_DOMAIN}
      HMDM_URL: http://${BASE_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      DISABLE_HTTPS: "true"
      SKIP_DOWNLOAD: "true"
      FORCE_RECONFIGURE: "false"
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
