version: "3.8"

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - hmdmnet

  hmdm:
    image: headwindmdm/hmdm:0.1.5
    restart: unless-stopped
    ports:
      - "8189:8080"
      - "31000:31000"
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
      - ./volumes/letsencrypt:/etc/letsencrypt
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      PROTOCOL: http
      BASE_DOMAIN: ${BASE_DOMAIN}
      HMDM_URL: http://${BASE_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SHARED_SECRET: ${SHARED_SECRET}
      HMDM_VARIANT: ${HMDM_VARIANT}
      CLIENT_VERSION: ${CLIENT_VERSION}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}
      DISABLE_HTTPS: true
      SKIP_DOWNLOAD: true
    networks:
      - hmdmnet

networks:
  hmdmnet:
    driver: bridge
