version: "3.3"

services:
  # ──────────────────────────────────────────
  # Database
  # ──────────────────────────────────────────
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    expose:
      - "5432"          # only inside the Docker network

  # ──────────────────────────────────────────
  # Headwind MDM
  # ──────────────────────────────────────────
  hmdm:
    image: headwindmdm/hmdm:0.1.5
    restart: unless-stopped

    # ▸ Coolify will publish HTTPS for you.
    #   Map *one* free host port → internal 8080 (Tomcat HTTP)
    ports:
      - "8189:8080"       # <host>:<container>
      - "31000:31000"     # device-sync port (leave as-is)

    volumes:
      - ./volumes/work:/usr/local/tomcat/work   # temp files / uploads
      # keep the letsencrypt mount; Traefik stores certs here
      - ./volumes/letsencrypt:/etc/letsencrypt

    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}

      # Headwind served by Traefik → talk HTTP internally
      PROTOCOL: http
      BASE_DOMAIN: ${BASE_DOMAIN}     # mdm.tehub.co.uk
      LOCAL_IP: 0.0.0.0
      ADMIN_EMAIL: ${ADMIN_EMAIL}

      SHARED_SECRET: ${SHARED_SECRET}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      HMDM_URL: http://${BASE_DOMAIN}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}

volumes:
  db_data:
