version: "3"

services:
  postgresql:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    expose:
      - "5432"
    networks: [hmdmnet]

  hmdm:
    image: headwindmdm/hmdm:0.1.5
    restart: unless-stopped
    depends_on: [postgresql]
    ports:
      - "8080"            # INTERNAL for Coolify / Traefik
      - "31000:31000"     # device sync
    env_file: .env        # change to .env.preview for preview stack
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
      - ./volumes/letsencrypt:/etc/letsencrypt
    networks: [hmdmnet]

networks:
  hmdmnet:
    driver: bridge
