version: "3.8"

services:
  postgresql:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    expose:
      - "5432"                # internal-only; no host clash

  hmdm:
    image: headwindmdm/hmdm:0.1.5
    restart: unless-stopped
    ports:
      - "8189:8080"           # host 8189 → Tomcat 8080
      - "31000:31000"         # device sync
    volumes:
      - ./volumes/work:/usr/local/tomcat/work
      - ./volumes/letsencrypt:/etc/letsencrypt   # Traefik stores certs
    environment:
      SQL_HOST: postgresql
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}

      PROTOCOL: http                          # handled by Traefik
      BASE_DOMAIN: ${BASE_DOMAIN}             # mdm.tehub.co.uk
      HMDM_URL: http://${BASE_DOMAIN}         # internal URL
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      SHARED_SECRET: ${SHARED_SECRET}
      HMDM_VARIANT: ${HMDM_VARIANT}
      DOWNLOAD_CREDENTIALS: ${DOWNLOAD_CREDENTIALS}
      CLIENT_VERSION: ${CLIENT_VERSION}
      FORCE_RECONFIGURE: ${FORCE_RECONFIGURE}
volumes:
  db_data:
